services:
  postgres:
    container_name: scholar_ai_db
    image: postgres:17.5
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: scholarAI
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres: